const fs = require('fs');
const path = require('path');
const { withDangerousMod, withSettingsGradle } = require('@expo/config-plugins');

// P1B — build durability only. P1A placed the Wear OS `:wearapp` Gradle
// module and its `settings.gradle` include directly inside `android/`,
// which is gitignored and fully regenerated by `expo prebuild` -- so a
// future prebuild would silently erase both. This plugin is the fix: the
// real, git-tracked source of truth for the Wear OS module now lives at
// `wearos/wearapp/` (outside any generated/gitignored directory), and this
// plugin copies it into `android/wearapp/` and adds the matching
// `settings.gradle` include every time `expo prebuild` regenerates Android.
//
// Deliberately does NOT touch `android/app` or anything under it -- the
// existing production `app.bookwithai.app` module and its build config,
// signing, versionCode, etc. are entirely untouched by this plugin. No new
// wearable feature is added here (no voice, notifications, Tiles, actions,
// customer features, or background sync) -- this only makes the P1A
// foundation (NEXT/TODAY glance) survive a prebuild.

const WEAR_MODULE_NAME = 'wearapp';
const WEAR_SOURCE_DIR = path.join(__dirname, '..', 'wearos', WEAR_MODULE_NAME);
const SETTINGS_GRADLE_MARKER = `include ':${WEAR_MODULE_NAME}'`;

/** Recursively copies the durable Wear OS module source into the generated android/ project. */
function copyWearModule(androidProjectRoot) {
  const destDir = path.join(androidProjectRoot, WEAR_MODULE_NAME);
  fs.rmSync(destDir, { recursive: true, force: true });
  fs.cpSync(WEAR_SOURCE_DIR, destDir, { recursive: true });
}

/** Idempotently adds `include ':wearapp'` to settings.gradle if not already present. */
function withWearSettingsGradle(config) {
  return withSettingsGradle(config, (config) => {
    if (config.modResults.contents.includes(SETTINGS_GRADLE_MARKER)) {
      return config;
    }
    config.modResults.contents = config.modResults.contents.replace(
      /include ':app'/,
      `include ':app'\n` +
        `// Standalone Wear OS companion app -- its own Gradle module/APK, distributed\n` +
        `// separately, communicating with :app only via the Android Wearable Data\n` +
        `// Layer API (no \`wearApp project(...)\` embedding -- that mechanism is legacy\n` +
        `// pre-Wear-OS-3 guidance). Source of truth: wearos/wearapp/ (see\n` +
        `// plugins/withWearOsModule.js), copied here fresh on every prebuild.\n` +
        `${SETTINGS_GRADLE_MARKER}`
    );
    return config;
  });
}

function withWearAppCopy(config) {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      copyWearModule(config.modRequest.platformProjectRoot);
      return config;
    },
  ]);
}

function withWearOsModule(config) {
  config = withWearSettingsGradle(config);
  config = withWearAppCopy(config);
  return config;
}

module.exports = withWearOsModule;
